import numpy as np

A = np.array([[1,2],[3,4]])
print("A Matrix: ")
print(A)
print("A Matrix det(): ")
print(np.linalg.det(A))
B = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3], [3, 1]] ])
print("B Matrix: ")
print(B)
print("B Matrix det(): ")
print(np.linalg.det(B))
C=np.array([[2,7],[8,4]])
print("C Matrix: ")
print(C)
print("C Matrix det(): ")
print(np.linalg.det(C))
print("det(A*C): ", np.linalg.det(np.dot(A,C)))
print("det(A)*det(C): ", np.linalg.det(A)*np.linalg.det(C))